### ISSUE TITLE
Add you plugins to the community plugin directory

### ISSUE THREAD

**Issue by tudi2d** [sammbetts/backstage-plugin-service-health#1]
Hej @sammbetts,

great to see your status page & service health plugins!! 🎉 Would you be interested in adding them to the [community plugin directory](https://backstage.io/plugins/) ([Guide](https://backstage.io/docs/plugins))? This way you would make it easier for the community to find them, use them & hopefully contribute back to them! :)

Good work & have a great day!
Philipp :)

**Comment by sammbetts** [comment]
Hello! Yes I would love to add to the directory - I have raised an issue for this, but I need to do a little bit more development :)
